pipeline {
    agent any

    stages{
        stage("sonarcloud analysis"){
            steps{
                withSonarQubeEnv('sonarcloud'){
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Hossnia_testt'
                }
            }
        }
    }
}