pipeline {
    agent any

    stages{
        stage("sonarcloud analysis"){
            withSonarQubeEnv('sonarcloud'){
                steps{
                    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Hossnia_testt'
                }
            }
        }
    }
}